-- MySQL Script generated by MySQL Workbench
-- Tue Feb  1 13:09:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET DATESTYLE TO PostgresSQL, European ;
-- -----------------------------------------------------
-- Drops
-- -----------------------------------------------------

DROP TABLE IF EXISTS CLUB CASCADE;
DROP TABLE IF EXISTS EQUIPO CASCADE;
DROP TABLE IF EXISTS JUGADOR CASCADE;
DROP TABLE IF EXISTS PERSONAL CASCADE;
DROP TABLE IF EXISTS ARBITRO CASCADE;
DROP TABLE IF EXISTS NO_OFICIAL CASCADE;
DROP TABLE IF EXISTS OFICIAL CASCADE;
DROP TABLE IF EXISTS LIGA CASCADE;
DROP TABLE IF EXISTS EMPRESA CASCADE;
DROP TABLE IF EXISTS EMPRESA_patrocina_LIGA CASCADE;

-- -----------------------------------------------------
-- Table CLUB
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CLUB (
  Nombre_club VARCHAR(45) NOT NULL,
  Calle VARCHAR(45) NULL,
  Numero_calle INT NULL,
  DNI_Presidente VARCHAR(9) NULL,
  Telefono INT NULL,
  PRIMARY KEY (Nombre_club))
;


-- -----------------------------------------------------
-- Table EQUIPO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS EQUIPO (
  Nombre_equipo VARCHAR(45) NOT NULL,
  CLUB_Nombre_club VARCHAR(45) NOT NULL,
  Logotipo bytea NULL,
  Categoria VARCHAR(45) NULL,
  Acronimo VARCHAR(3) NULL,
  PRIMARY KEY (Nombre_equipo),
  CONSTRAINT fk_EQUIPO_CLUB
    FOREIGN KEY (CLUB_Nombre_club)
    REFERENCES CLUB (Nombre_club)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table JUGADOR
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS JUGADOR (
  DNI VARCHAR(9) NOT NULL,
  EQUIPO_Nombre_equipo VARCHAR(45) NOT NULL,
  Nombre VARCHAR(45) NULL,
  Correo VARCHAR(45) NULL,
  Dorsal INT NULL,
  Rol VARCHAR(45) NULL,
  Salario FLOAT NULL,
  PRIMARY KEY (DNI),
  CONSTRAINT fk_JUGADOR_EQUIPO1
    FOREIGN KEY (EQUIPO_Nombre_equipo)
    REFERENCES EQUIPO (Nombre_equipo)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table PERSONAL
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS PERSONAL (
  DNI VARCHAR(9) NOT NULL,
  EQUIPO_Nombre_equipo VARCHAR(45) NOT NULL,
  Nombre VARCHAR(45) NULL,
  Correo VARCHAR(45) NULL,
  Puesto VARCHAR(45) NULL,
  Salario FLOAT NULL,
  PRIMARY KEY (DNI),
  CONSTRAINT fk_PERSONAL_EQUIPO1
    FOREIGN KEY (EQUIPO_Nombre_equipo)
    REFERENCES EQUIPO (Nombre_equipo)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table EMPRESA
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS EMPRESA (
  CIF VARCHAR(9) NOT NULL,
  Nombre VARCHAR(45) NULL,
  Correo VARCHAR(45) NULL,
  PRIMARY KEY (CIF))
;


-- -----------------------------------------------------
-- Table ARBITRO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS ARBITRO (
  DNI VARCHAR(9) NOT NULL,
  Salario FLOAT NULL,
  Correo VARCHAR(45) NULL,
  Nombre VARCHAR(45) NULL,
  PRIMARY KEY (DNI))
;


-- -----------------------------------------------------
-- Table NO_OFICIAL
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS NO_OFICIAL (
  Calle VARCHAR(45) NOT NULL,
  Numero_calle INT NOT NULL,
  Fecha DATE NOT NULL,
  EQUIPO_Nombre_equipo VARCHAR(45) NOT NULL,
  ARBITRO_DNI VARCHAR(9) NOT NULL,
  PRIMARY KEY (Calle, Numero_calle, Fecha, EQUIPO_Nombre_equipo),
  CONSTRAINT fk_NO_OFICIAL_ARBITRO1
    FOREIGN KEY (ARBITRO_DNI)
    REFERENCES ARBITRO (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_NO_OFICIAL_EQUIPO1
    FOREIGN KEY (EQUIPO_Nombre_equipo)
    REFERENCES EQUIPO (Nombre_equipo)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table LIGA
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS LIGA (
  Año INT NOT NULL,
  Nombre_liga VARCHAR(45) NOT NULL,
  EMPRESA_CIF VARCHAR(9) NOT NULL,
  PRIMARY KEY (Año, Nombre_liga),
  CONSTRAINT fk_LIGA_EMPRESA1
    FOREIGN KEY (EMPRESA_CIF)
    REFERENCES EMPRESA (CIF)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table OFICIAL
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS OFICIAL (
  Calle VARCHAR(45) NOT NULL,
  Numero_calle INT NOT NULL,
  Fecha DATE NOT NULL,
  LIGA_Año INT NOT NULL,
  LIGA_Nombre_liga VARCHAR(45) NOT NULL,
  EQUIPO_Nombre_equipo VARCHAR(45) NOT NULL,
  ARBITRO_DNI VARCHAR(9) NOT NULL,
  PRIMARY KEY (Calle, Numero_calle, Fecha, LIGA_Año, LIGA_Nombre_liga, EQUIPO_Nombre_equipo),
  CONSTRAINT fk_OFICIAL_LIGA1
    FOREIGN KEY (LIGA_Año , LIGA_Nombre_liga)
    REFERENCES LIGA (Año , Nombre_liga)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_OFICIAL_ARBITRO
    FOREIGN KEY (ARBITRO_DNI)
    REFERENCES ARBITRO (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_OFICIAL_EQUIPO
    FOREIGN KEY (EQUIPO_Nombre_equipo)
    REFERENCES EQUIPO (Nombre_equipo)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table EMPRESA_patrocina_LIGA
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS EMPRESA_patrocina_LIGA (
  PATROCINADOR_CIF VARCHAR(9) NOT NULL,
  LIGA_Año INT NOT NULL,
  LIGA_Nombre_liga VARCHAR(45) NOT NULL,
  Inversion FLOAT NULL,
  PRIMARY KEY (PATROCINADOR_CIF, LIGA_Año, LIGA_Nombre_liga),
  CONSTRAINT fk_PATROCINADOR_has_LIGA_PATROCINADOR1
    FOREIGN KEY (PATROCINADOR_CIF)
    REFERENCES EMPRESA (CIF)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_PATROCINADOR_has_LIGA_LIGA1
    FOREIGN KEY (LIGA_Año , LIGA_Nombre_liga)
    REFERENCES LIGA (Año , Nombre_liga)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;